### ISSUE TITLE
Plugin no longer working in 1.19

### ISSUE THREAD

**Issue by TonyGravagno** [Masstrix/Eternal-Light#19]
Someone in the Spigot discussion area noted that something in 1.19.3 might have broken this plugin and others.
Eternal-Light 1.8 is not working in MC 1.19.4. We can set the config file and issue /LL commands but everything is ignored and there is no change to the UI to show light levels. No errors are reported in the server console.

I can look at this if required. Anyone else?

TY

**Comment by Masstrix** [comment]
Not sure exactly what the cause of that would be as I haven't taken a look at recent versions of spigot. If you know what the issue is feel free to make a pull request and I can update the spigot download page.

I might take a look at some point to see what the reason for this is. The plugin uses no nms so it's likely something to do with an api change between versions.

**Comment by TonyGravagno** [comment]
Thanks Matthew. I haven't looked at the code for a couple years but I'll take another look. I have little confidence that I'll be able to solve this - I never was that studly with these plugins. It would be nice if **anyone** in Discord could confirm that they're actually using the plugin in 1.19.x.
Ciao for now.

**Comment by helmasaur** [comment]
I'm using it on a Paper server version 1.19.3 and this plugin works for me.

**Comment by TonyGravagno** [comment]
Um, this was a user error (finger pointing at me). We forgot that in addition to setting /LL MODE Z, we also need to simply /LL with no options to Toggle the particles. Oy Ve.

This was a good exercise. I got familiar with the latest version (1.8) code and did make a couple minor tweaks.
I'll look at the permissions issue as time permits.

Closing as "No change required, hardware error, loose nut behind the keyboard" 😉
